# Generated by Django 3.1 on 2020-08-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200, verbose_name='address state')),
                ('city', models.CharField(max_length=200, verbose_name='address city')),
                ('zipcode', models.CharField(max_length=12, verbose_name='zip code / postal code')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='student first name')),
                ('lastname', models.CharField(max_length=250, verbose_name='student first name')),
                ('birthdate', models.DateTimeField(verbose_name='student birthdate')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_backend.address', verbose_name='the related address')),
            ],
        ),
    ]
