# Generated by Django 3.1 on 2020-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=250, verbose_name='student last name'),
        ),
    ]
